### ISSUE TITLE
For macOS do we need to add associated domain capability?

### ISSUE THREAD

**Issue by chunsfire** [DavBfr/flutter_u2f#1]
In order to implement webauthn passkey registration or authentication flow, macOS mandates to have associated domain capability added. This is due to underlying ASAuthorization framework.

So does this package also need associated domain capability enabled & added in the project?

**Comment by DavBfr** [comment]
It doesn't. It talks directly to the USB key at low level, bypassing the OS frameworks.

**Comment by chunsfire** [comment]
thanks for clarification :)
